name: DAVPy_demos2025
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - scikit-image
  - cellpose
  - seaborn 
  - dask
  - distributed 
  - napari 
  - pyqt
  - streamlit
  - scikit-learn
  - spacy
  - pytorch
  - torchvision
  - voila 
  - ipympl
  - ipywidgets
  - ipykernel
  - transformers
  - accelerate
  - zarr
  - s3fs
  - python-graphviz
